{
 "title": "Consul",
 "description": "Get performance metrics from Consul",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consul",
    "query": "label_values(consul_memberlist_gossep_sum, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consul Leader",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "consul_raft_leader_lastcontact_count",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "# servers in cluster",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "COUNT (changes(consul_memberlist_gossep_sum[1m]) > 0) BY (labels)"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu{mode=\"idle\", host=\"$consul\"}[1m])) * 100 / count_scalar(node_cpu{mode=\"user\", host=\"$consul\"})"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load1{host=\"$consul\"}"
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load5{host=\"$consul\"}"
    }
   ]
  },
  {
   "title": "Load 15",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load15{host=\"$consul\"}"
    }
   ]
  },
  {
   "title": "Memberlist TCP Messages",
   "type": "graph",
   "description": "The amount of TCP messages that are sent/received from the server.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(consul_memberlist_tcp{host=\"$consul\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memberlist UDP Messages",
   "type": "graph",
   "description": "The amount of UDP messages that are sent/received from the server.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(consul_memberlist_udp{host=\"$consul\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log replication from leader to servers",
   "type": "graph",
   "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul servers, as well as the performance of the communication between the servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_replication_appendEntries_rpc",
     "legendFormat": "{{query}} - {{quantile}}%"
    }
   ]
  },
  {
   "title": "consul_raft_replication_heartbeat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_replication_heartbeat",
     "legendFormat": "{{query}} - {{quantile}}%"
    }
   ]
  },
  {
   "title": "Write logs",
   "type": "graph",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_leader_dispatchLog", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Commit time Leader",
   "type": "graph",
   "description": "This measures the time it takes to commit a new entry to the Raft log on the leader.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_commitTime", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "graph",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "delta(consul_raft_apply[30s])", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "Leader lastContact",
   "type": "graph",
   "description": "This will only be emitted by the Raft leader and measures the time since the leader was last able to contact the follower nodes when checking its leader lease. It can be used as a measure for how stable the Raft timing is and how close the leader is to timing out its lease.\n\nThe lease timeout is 500 ms times the raft_multiplier configuration, so this telemetry value should not be getting close to that configured value, otherwise the Raft timing is marginal and might need to be tuned, or more powerful servers might be needed. See the Server Performance guide for more details.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_leader_lastcontact", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(consul_rpc_query{host=\"$consul\"}[30s])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Serf Coordinates",
   "type": "graph",
   "description": "Consul uses a network tomography system to compute network coordinates for nodes in the cluster. These coordinates allow the network round trip time to be estimated between any two nodes using a very simple calculation. This allows for many useful applications, such as finding the service node nearest a requesting node, or failing over to services in the next closest datacenter.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_serf_coordinate_adjustment_ms{host=\"$consul\"}",
     "legendFormat": "{{quantile}}%"
    }
   ]
  }
 ]
}