{
 "title": "Vault",
 "description": " ",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Modify by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"create|delete|renew\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "title": "Read by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"read\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(vault_sys_sealed{}[15s])"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(vault_sys_initialized{}[15s])"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pending Tokens",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vault_token_create_count-vault_token_store_count"
    }
   ]
  },
  {
   "title": "Token Lookup",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_token_lookup_count[1m])",
     "legendFormat": "Lookup"
    }
   ]
  },
  {
   "title": "Token",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vault_token_create_count", "legendFormat": "Create" },
    { "expr": "vault_token_store_count", "legendFormat": "Store" }
   ]
  },
  { "title": "Audit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Audit Log Request",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(vault_audit_log_request_count[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "sum(irate(vault_audit_log_response_count[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "sum(irate(vault_core_handle_request_count[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Auth Rollback",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vault_route_count{method=~\"rollback\"}[5m])) by (method, path)",
     "legendFormat": "{{ method }}:{{path}}"
    }
   ]
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Policy Set",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_set_policy_count[1m]))",
     "legendFormat": "set"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Google Cloud Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Cloud Storage List",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(irate(vault_gcs_list_count[10m]))",
     "legendFormat": "list"
    }
   ]
  },
  {
   "title": "Cloud Storage GET",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vault_gcs_get_count[10m])", "legendFormat": "GET" }
   ]
  },
  {
   "title": "Cloud Storage Delete",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vault_gcs_delete_count[10m])",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Cloud Storage PUT",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(vault_gcs_put_sum[5m])", "legendFormat": "PUT" }
   ]
  }
 ]
}